# -*- coding: utf-8 -*-

from odoo import models, fields, api, _


class ResPartner(models.Model):
    _inherit = 'res.partner'

    entity_id = fields.Integer(string='Entity ID', readonly=True)
    entity_address_type = fields.Selection([
        ('postal', 'Postal Address'),
        ('physical', 'Physical Address'),
    ], string='Entity Address Type', readonly=True)
    home_phone = fields.Char(string='Home Phone', readonly=True)
    outlook_id = fields.Integer(string='Outlook ID', readonly=True)
    # Address fields
    address_2 = fields.Char('Address 2', readonly=True)
    address_3 = fields.Char('Address 3', readonly=True)
    code = fields.Char('Code', readonly=True)
    region = fields.Char('Region', readonly=True)
    temp_id = fields.Char('TempID', readonly=True)
    is_default = fields.Char('Is Default', readonly=True)
    address_4 = fields.Char('Address 4', readonly=True)
    # Contact fields
    dealer_id = fields.Char('Dealer ID', readonly=True)
    company = fields.Char('Company', readonly=True)
    entity_type_id = fields.Char('Entity Type ID', readonly=True)
    entity_category_id = fields.Char('Entity Category ID', readonly=True)
    entity_creator_id = fields.Char('Entity Creator ID', readonly=True)
    entity_updater_id = fields.Char('Entity Updater ID', readonly=True)
    abc_cat_id = fields.Char('ABC Cat ID', readonly=True)
    bus_cat_id = fields.Char('BUS Cat ID', readonly=True)
    notes = fields.Char('Notes', readonly=True)
    date_added = fields.Char('Date Added', readonly=True)
    date_modified = fields.Char('Date Modified', readonly=True)
    switchboard = fields.Char('Switchboard', readonly=True)
    fax = fields.Char('Fax', readonly=True)
    url = fields.Char('URL', readonly=True)
    vat_except_num = fields.Char('VAT Except Number', readonly=True)
    accept_back_orders = fields.Char('Accept Back Orders', readonly=True)
    menthod_of_contact = fields.Char('Method Of Contact', readonly=True)
    catdesc = fields.Char('Catdesc', readonly=True)
    comptel = fields.Char('Comptel', readonly=True)
    next_call_date = fields.Char('Next Call Date', readonly=True)
    account_type_id = fields.Char('Account Type ID', readonly=True)
    date_updated = fields.Char('Date Updated', readonly=True)
    compregnum = fields.Char('Compregnum', readonly=True)
    account_num = fields.Char('Account Number', readonly=True)
    modified_by = fields.Char('Modified By', readonly=True)
    account_supplier_id = fields.Char('Account Supplier ID', readonly=True)
    account_customer_id = fields.Char('Account Customer ID', readonly=True)
    is_birthday_supplier = fields.Char('Is Birthday Supplier', readonly=True)
    is_birthday_courier = fields.Char('Is Birthday Courier', readonly=True)
    is_anniversary_courier = fields.Char('Is Anniversary Courier', readonly=True)
    is_anniversary_supplier = fields.Char('Is Anniversary Supplier', readonly=True)
    is_account_supplier = fields.Char('Is Account Supplier', readonly=True)
    is_supplier = fields.Char('Is Supplier', readonly=True)
    invoice_to = fields.Char('Invoice To', readonly=True)
    currency = fields.Char('Currency', readonly=True)
    credit_limit = fields.Char('Credit Limit', readonly=True)
    payment_terms = fields.Char('Payment Terms', readonly=True)
    sdl_no = fields.Char('SDL No', readonly=True)
    sic_code = fields.Char('Sic Code', readonly=True)
    ofo_no = fields.Char('OFO No', readonly=True)
    markup = fields.Char('Markup', readonly=True)
    client_rating = fields.Char('Client Rating', readonly=True)
    manual_rating = fields.Char('Manual Rating', readonly=True)
    sales_cons_id = fields.Char('Sales Cons ID', readonly=True)
    alternate_company_id = fields.Char('Alternate Company ID', readonly=True)
    comments = fields.Char('Comments', readonly=True)
    card_type_id = fields.Char('Card Type ID', readonly=True)
    credit_card_name = fields.Char('Credit Card Name', readonly=True)
    credit_card_number = fields.Char('Credit Card Number', readonly=True)
    exp_month = fields.Char('Exp Month', readonly=True)
    exp_year = fields.Char('Exp Year', readonly=True)
    bank_recon_notes = fields.Char('Bank Recon Notes', readonly=True)
    acc_stat_id = fields.Char('Acc Stat ID', readonly=True)
    avg_payment_time = fields.Char('Avg Payment Time', readonly=True)
    vendor_number = fields.Char('Vendor Number', readonly=True)
    source_id = fields.Char('Source ID', readonly=True)
    pricelistID = fields.Char('Pricelist ID', readonly=True)
    bank_branch_name = fields.Char('Bank Branch Name', readonly=True)
    bank_branch_code = fields.Char('Bank Branch Code', readonly=True)
    debit_order = fields.Char('Debit Order', readonly=True)
    ref_no = fields.Char('Ref No', readonly=True)
    tax_type_id = fields.Char('Tax Type ID', readonly=True)
    industry_id = fields.Char('Industry ID', readonly=True)
    entity_subtype_id = fields.Char('Entity Subtype ID', readonly=True)
    temp_id_varchar = fields.Char('Temp ID Varchar', readonly=True)
    is_vat_exempt = fields.Char('Is VAT Exempt', readonly=True)
    in_active = fields.Char('In Active', readonly=True)
    cnt_order_number = fields.Char('Cnt Order Number', readonly=True)
    cnt_id_number = fields.Char('Cnt ID Number', readonly=True)
    cnt_damage_waiver = fields.Char('Cnt Damage Waiver', readonly=True)
    cnt_sites = fields.Char('Cnt Sites', readonly=True)
    # Entity contact fields
    alternate_contact_id = fields.Char('Alternate Contact ID', readonly=True)
    entity_contact_updater_id = fields.Char('Entity Contact Updater ID', readonly=True)
    entity_contact_creator_id = fields.Char('Entity Contact Creater ID', readonly=True)
    physical_addr_id = fields.Char('Physical Address ID', readonly=True)
    postal_addr_id = fields.Char('Postal Addr ID', readonly=True)
    cont_type_id = fields.Char('Cont Type ID', readonly=True)
    position_id = fields.Char('Position ID', readonly=True)
    phone2 = fields.Char('Phone 2', readonly=True)
    phone3 = fields.Char('Phone 3', readonly=True)
    ext = fields.Char('EXT', readonly=True)
    department = fields.Char('Department', readonly=True)
    spouse = fields.Char('Spouse', readonly=True)
    asst_title = fields.Char('Asst Title', readonly=True)
    asst_name = fields.Char('Asst Name', readonly=True)
    asst_phone = fields.Char('Asst Phone', readonly=True)
    asst_ext = fields.Char('Asst Ext', readonly=True)
    hobbies = fields.Char('Hobbies', readonly=True)
    poaddress1 = fields.Char('PO Address 1', readonly=True)
    poaddress2 = fields.Char('PO Address 2', readonly=True)
    poaddress3 = fields.Char('PO Address 3', readonly=True)
    pocity = fields.Char('PO City', readonly=True)
    postate = fields.Char('PO State', readonly=True)
    pocode = fields.Char('PO Code', readonly=True)
    poregion = fields.Char('PO Region', readonly=True)
    pocountry = fields.Char('PO Country', readonly=True)
    birth_date = fields.Char('Birth Date', readonly=True)
    path = fields.Char('Path', readonly=True)
    province = fields.Char('Province', readonly=True)
    send_email = fields.Char('Send Email', readonly=True)
    send_sms = fields.Char('Send SMS', readonly=True)
    entity_htype = fields.Char('Entity Htype', readonly=True)
    owning_user_id = fields.Char('Owning User ID', readonly=True)
    position = fields.Char('Position', readonly=True)
    asstemail = fields.Char('Asst Email', readonly=True)
    sendpost = fields.Char('Send Post', readonly=True)
    dissacosiate = fields.Char('Dissacosiacte', readonly=True)
    birthday_supplier_id = fields.Char('Birthday Supplier ID', readonly=True)
    birthday_courier_id = fields.Char('Birthday Courier ID', readonly=True)
    anniversary_supplier_id = fields.Char('Anniversary Supplier ID', readonly=True)
    anniversary_courier_id = fields.Char('Anniversary Courier ID', readonly=True)
    anniversary_date = fields.Char('Birthday Courier ID', readonly=True)
    account_ref = fields.Char('Account Ref', readonly=True)
    id_number = fields.Char('ID Number', readonly=True)
    bank_name = fields.Char('Bank Name', readonly=True)
    account_no = fields.Char('Account No', readonly=True)
    account_name = fields.Char('Account Name', readonly=True)
    bank_account_name = fields.Char('Bank Account Name', readonly=True)
    branch_code = fields.Char('Branch Code', readonly=True)
    acc_type_id = fields.Char('Acc Type ID', readonly=True)
    emailref = fields.Char('Email Ref', readonly=True)
    expiry_date = fields.Char('Expiry Date', readonly=True)
    is_credit_card = fields.Char('Is Credit Card', readonly=True)
    in_use = fields.Char('In Use', readonly=True)
    agent_ref = fields.Char('Agent Ref', readonly=True)
    agent_id = fields.Char('Agent ID', readonly=True)
    press = fields.Char('Press', readonly=True)
    proj_cust = fields.Char('Proj Cust', readonly=True)
    completed = fields.Char('Completed', readonly=True)
    department_id = fields.Char('Department ID', readonly=True)
    use_comp_addr = fields.Char('Use Comp Addr', readonly=True)
    additional1 = fields.Char('Additional 1', readonly=True)
    additional2 = fields.Char('Additional 2', readonly=True)
    additional3 = fields.Char('Additional 3', readonly=True)
    additional4 = fields.Char('Additional 4', readonly=True)
    additional_id5 = fields.Char('Additional ID 5', readonly=True)
    additional_id6 = fields.Char('Additional ID 6', readonly=True)
    additional_id7 = fields.Char('Additional ID 7', readonly=True)
    additional_id8 = fields.Char('Additional ID 8', readonly=True)
    screenshot_path = fields.Char('Screenshot Path', readonly=True)

